version: "3.8"

services:
  database:
    image: postgres:13-alpine
    hostname: database
    volumes:
      - type: volume
        source: opengeo-database
        target: /var/lib/postgres/data
    environment:
      POSTGRES_USER: opengeo
      POSTGRES_PASSWORD: opengeodummypassword
      POSTGRES_DB: opengeo
    networks:
      - opengeo-net
    restart: unless-stopped

  backend:
    build: .
    image: ${PROJECT_REGISTRY}opengeo-backend:${CI_COMMIT_SHORT_SHA:-latest}
    command: >
      bash -c "ls -al &&
        python manage.py migrate &&
        uvicorn --host 0.0.0.0 --reload opengeo-project.asgi:application"
    volumes:
      - type: ${VOLUME_TYPE:-bind}
        source: ${VOLUME:-./config.production.yml}
        target: ${VOLUME_TARGET:-/app/config.yml}
        read_only: true
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - opengeo-net
    labels:
      - "traefik.enable=true"
      - "compose.stack=opengeo-complete"
      # http
      - "traefik.http.services.opengeo-api.loadbalancer.server.port=8000"
      - "traefik.http.routers.opengeo-api.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.opengeo-api.entrypoints=web"

  frontend:
    build: 
        context: ./opengeo-frontend
        dockerfile: ./opengeo-frontend/Dockerfile.production
    image: ${PROJECT_REGISTRY}opengeo-frontend:${FRONTEND_COMMIT_SHORT_SHA:-latest}
    ports: 
        - 127.0.0.1:3000:80/tcp
    volumes:
      - type: ${VOLUME_TYPE:-bind}
        source: ${VOLUME:-./opengeo-frontend/docker}
        target: ${VOLUME_TARGET:-/app}
        read_only: true
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - opengeo-net
    labels:
      - "traefik.enable=true"
      - "compose.stack=opengeo-complete"
      - "traefik.http.services.opengeo.loadbalancer.server.port=80"
      # http
      - "traefik.http.routers.opengeo.rule=hostregexp(`{host:.+}`) && PathPrefix(`/app`)"
      - "traefik.http.routers.opengeo.entrypoints=web"
      - "traefik.http.routers.opengeo.middlewares=strip-app-prefix-regex"
      - "traefik.http.middlewares.strip-app-prefix-regex.stripprefixregex.regex=/app((?:/[^/.]*)*)?"
      # static files + /app/file.ext
      - "traefik.http.routers.opengeo-files.rule=hostregexp(`{host:.+}`) && PathPrefix(`/app/static`, `/app/[a-zA-Z0-9]+.[a-zA-Z0-9]+`)"
      - "traefik.http.routers.opengeo-files.entrypoints=web"
      - "traefik.http.routers.opengeo-files.middlewares=strip-app-prefix"
      - "traefik.http.middlewares.strip-app-prefix.stripprefix.prefixes=/app"

  proxy:
    image: traefik:v2.4
    command:
      - "--log.level=INFO"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.constraints=Label(`compose.stack`,`opengeo-complete`)"
    ports:
      - 0.0.0.0:80:80/tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: yes
    restart: unless-stopped
    networks:
      - opengeo-net

networks:
  opengeo-net:

volumes:
  opengeo-database:
  opengeo-config:
    external: true
