FROM osgeo/gdal:ubuntu-small-3.2.3 as build-stage

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

RUN apt-get update && \
    apt-get -y install --no-install-recommends gcc g++ python3-distutils python3-dev python3-pip && \
    pip3 install poetry && \
    rm -rf /var/lib/apt/lists/*
