# Generated by Django 3.2.3 on 2021-05-29 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('time_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LobbyGameModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_lobbies', to='opengeo.gamemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='opengeo.gamemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('open', 'Open'), ('running', 'Running'), ('closed', 'Closed')], default='open', max_length=10)),
                ('name', models.CharField(default=uuid.uuid4, max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('lobby_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to='opengeo.lobbygamemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyPlayerModel',
            fields=[
                ('state', models.CharField(choices=[('idle', 'Idle'), ('ready', 'Ready'), ('in_game', 'In Game'), ('waiting_next_round', 'Waiting Next Round'), ('after_game', 'After Game'), ('searching_lobby', 'Searching Lobby')], default='searching_lobby', max_length=20)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lobby_player', serialize=False, to='opengeo.playermodel')),
                ('lobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_players', to='opengeo.lobbymodel')),
            ],
        ),
        migrations.CreateModel(
            name='GuessModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('guess_start', models.DateTimeField(auto_now=True)),
                ('guess_end', models.DateTimeField(blank=True, null=True)),
                ('lobby_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='opengeo.lobbygamemodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='opengeo.locationmodel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='opengeo.lobbyplayermodel')),
            ],
        ),
    ]
