# Generated by Django 3.2.4 on 2021-06-02 23:14

from django.db import migrations, models
import django.db.models.deletion
import opengeo.models


class Migration(migrations.Migration):

    dependencies = [
        ('opengeo', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM opengeo_gamemodel"),
        migrations.AlterModelManagers(
            name='playermodel',
            managers=[
                ('objects', opengeo.models.PlayerManager()),
            ],
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='opengeo.playermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guessmodel',
            name='guess_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
